### ISSUE TITLE
Explain what this does better than the native syntax?

### ISSUE THREAD

**Issue by jorhett** [webiny/action-post-run#5]
It's hard to grasp why this action exists, as this feature set is built into Actions today. If this provides a value not provided by GitHub Actions syntax you should add it to the documentation.

The documentation's example runs exactly the same, and much faster, written as the following:

```yaml
jobs:
  something:
    name: Do something...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - id: post-run-command
        needs: non-existent-command
        if: ${{ always() }}
        run: echo "this thing works!"

      - id: another-post-run-command
        needs: non-existent-command
        if: ${{ always() }}
        run: echo "this thing works again!"
        working-directory: not-required-but-you-can-provide-it

      - id: non-existent-command
        name: 'Running an non-existing command will fail...'
        run: run something that does not exist;
```

**Comment by ftzm** [comment]
Is this valid? I don't believe it's possible to specify "needs" on individual steps. I can find no documentation for it, and it doesn't work when I try it. Maybe I'm missing something.

**Comment by Piedone** [comment]
It doesn't work, You need to execute post-job code in a JavasScript action with [`runs.post`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost).

**Comment by swissbuechi** [comment]
@jorhett 
Your solution does not work for me.
I acctually needed the following syntax to make the post step always run (even if some steps above fail):

```yaml
    - name: Show VPN log
      uses: webiny/action-post-run@3.0.0
      if: always()
      with:
        run: sudo cat vpn.log
```

Thanks to @adrians5j for publishing this action!
